version: "3"

services:

  exporter:
    container_name: exporter
    build:
      dockerfile: Dockerfile
      context: ../opcua_exporter
    image: aimirim/tocandira-exporter:0.2.0
    
  watchdog:
    container_name: watchdog_forte
    build:
      dockerfile: Dockerfile
      context: ../watchdog
    image: aimirim/tocandira-watchdog:0.2.0
