version: "3"
networks:
  forte-net:
    driver: bridge

services:

  exporter:
    container_name: exporter
    image: tocandira_exporter:0.2.0
    networks:
      - forte-net
    restart: always
    volumes: 
      - "$EXPORTER_CONFIG_LOCATION:/config/opcua_exporter.yml"
    ports:
      - "$METRICS_PORT:9686"
    command: [
      -config, /config/opcua_exporter.yml, 
      -read-timeout, "$EXPORTER_TIMEOUT",
      -max-timeouts, "$EXPORTER_MAX_TIMEOUT",
      -force-read, "$EXPORTER_FORCE_READ" ]
    logging:
      options:
        max-size: $LOG_RETENTION
  
  forte_server:
    container_name: forte_server
    image: forte:0.6.0-x86_64
    networks:
      - forte-net
    restart: always
    environment:
      FORTE_TYPE: RELEASE
    ports:
      - "61499"
      - "4840"
    volumes:
      - "$GATEWAY_FBOOT_LOCATION:/forte.fboot"
    command: [-op, '4840']
    logging:
      options:
        max-size: $LOG_RETENTION
  
  forte_tester:
    container_name: forte_tester
    image: forte:0.6.0-x86_64
    networks:
      - forte-net
    restart: always
    environment:
      FORTE_TYPE: RELEASE
    ports:
      - "61499"
      - "$TESTESERVER_PORT:4840"
    volumes:
      - "$TESTESERVER_FBOOT_LOCATION:/forte.fboot"
    command: [-op, '4840']
    logging:
      options:
        max-size: $LOG_RETENTION

  watchdog:
    container_name: watchdog_forte
    image: tocandira_watchdog:0.2.0
    networks:
      - forte-net
    restart: always
    environment:
      WATCH_FOLDER: /home
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/home/config
      - ./fboot:/home/fboot
    logging:
      options:
        max-size: $LOG_RETENTION

  hardware_monitor:
    container_name: hardware_monitor
    image: prom/node-exporter:v1.5.0
    network_mode: host
    pid: host
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave
    command: [
      '--path.rootfs=/host',
      '--web.disable-exporter-metrics',
      '--collector.disable-defaults',
      '--collector.cpu',
      '--collector.meminfo',
      '--collector.hwmon',
      '--collector.netdev',
      '--collector.filesystem',
      '--collector.filesystem.fs-types-exclude=.*(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|tmpfs|nfsd).*',
      '--collector.filesystem.mount-points-exclude=.*var/log.*',
      '--collector.diskstats',
    ]
    logging:
      options:
        max-size: $LOG_RETENTION
