# Copyright (c) 2017 Aimirim STI.

services:

  watchdog:
    container_name: watchdog_forte
    watch_files:
      - /home/config/monitoring.yml

  exporter:
    container_name: exporter
    watch_files:
      - /home/config/opcua_exporter.yml

  forte_server:
    container_name: forte_server
    watch_files:
      - /home/fboot/gw_opc.fboot

  forte_tester:
    container_name: forte_tester
    watch_files:
      - /home/fboot/opc_tester.fboot


